[package]
name = "gum-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tempfile = "3.12.0"
gum-core = { path = "../gum-core" }
tokio = "1.39.3"
anyhow = "1.0.86"


[[bin]]
name = "gum"
path = "src/main.rs"
